Add ExceptionFilter to log uncaught errors
safe-global/safe-client-gateway-nest pull request #528
Opened 2023-07-03 14:44 UTC by fmrsabino

Depends on #527 

- Adds an `ExceptionFilter` which logs all errors that do not have a filter associated with it.
- Errors were already being logged to the console (default NestJS logger behavior). This changes that default to use our own `ILoggingService`.
- Moves `DataSourceErrorFilter` from `AppProvider` into `AppModule` – the new exception filter requires dependency injection to be in place (which cannot be done via `app.useGlobalFilters()` and, in order to have a standard way of adding exception filters, both of them are now provided by `AppModule`

2023-07-03 15:06 UTC, fmrsabino commented
Moved to draft to add a test.

2023-07-04 09:33 UTC, fmrsabino commented
@safe-global/safe-client-gateway-maintainers ready for review

2023-07-04 15:47 UTC, hectorgomezv requested changes
Great job 🚀  just requested a small change.

2023-07-04 15:47 UTC, hectorgomezv commented on src/routes/common/filters/global-error.filter.spec.ts
> +  async bar() {
```suggestion
  async nonHttpException() {
```

2023-07-04 22:06 UTC, fmrsabino commented on src/routes/common/filters/global-error.filter.spec.ts
> +  async bar() {
Ups! 😅 Thank you! Added.

2023-07-05 09:10 UTC, hectorgomezv approved these changes

2023-07-05 09:11 UTC, merged